### PR TITLE
Home Page mockups

### PR DESCRIPTION
**Pull request by nkkl**
This pull request has the first mockup, for the Media Public landing page. The layout is fully responsive and is designed to be more touch-friendly at smaller screen sizes. The copy is not final; would like @melodykramer in particular to help me rough that out. Feedback on the rest of the design is more than welcome; although it has colors and fonts it is far from final.

**Screenshots**
image

image

### CODE REVIEW

**Comment by thequbit** [comment]
:+1:

**Comment by thequbit** [comment]
These look great! Thanks @nkkl!

**Comment by melodykramer** [comment]
I LOVE THESE.

**Comment by melodykramer** [comment]
I can work on copy this weekend @nkkl - I'm completely free and going in full time on this. I will try to catch you after work today.

**Comment by melodykramer** [comment]
Or if you want to send me length requirements / content types you need, we can work asynch.

**Comment by nkkl** [comment]
No plans after work today! Not sure how late I'll be in the office, but I only have one afternoon meeting so we can make it work.

**Pull request merged**
