### PR TITLE
Organization linking

### PR DESCRIPTION
**Pull request by GabeIsman**
This adds a reusable organization editor that uses typeahead to search through available organizations as the user types, and then converts that value to an organization_id for storage. This should be useful in a couple of places, but I've only added it to the user profile here.

### CODE REVIEW

**Comment by GabeIsman** [comment]
cc @ismcodes This should be useful for the recording page work you've been doing!

**Comment by ismcodes** [comment]
This will help a ton! Integrating soon.

**Comment by thequbit** [comment]
Looks like this may super-seed #169 ... @GabeIsman ?

**Comment by GabeIsman** [comment]
Yep. That works.

**Comment by GabeIsman** [comment]
@thequbit This work just depended on #169 so I included the commit here. If this is working for you and the other one isn't then, that's weird, but you can just merge this one and close the other. That'll work.

**Pull request merged**
