### PR TITLE
Organization page improvements

### PR DESCRIPTION
**Pull request by GabeIsman**
This adds a bunch of people related stuff to the organization page (in a way that should be easily shareable across pages). Some things aren't really integrated with the server yet (in part because the API's don't exist, see #112) and other integrations are very clunky (you can currently only edit the name of the person see #111). On balance though, I like to keep merging, rough edges and all, so my working copy doesn't drift too far from develop as I make broad changes.

Makes progress on #67 without quite getting all the way there (although recordings should be easier now that I've figured out more of how this should be set up).

### CODE REVIEW

**Comment by thequbit** [comment]
Will pull this down tonight/evening and merge afterwards.  Thanks @GabeIsman!

**Comment by thequbit** [comment]
:+1:

A few thoughts:
- I don't think we'll be adding people that way, but no harm in keeping it there right now.
- How do you envision grouping the stations by state?  Getting the JSON blob and then doing the sort in javascript, or should we think about doing that on the server side ( less desirable )?

**Comment by GabeIsman** [comment]
@thequbit Yep, totally agree on editing people (per our discussion earlier, and elsewhere). I just wanted a way to add stuff to the db to test the integration there. The editing stuff is actually only like four lines in the template :grin:. 

We can do the state grouping client-side. It'll be a while before we hit the scale where that's a real issue. That way we don't need any new endpoints.

**Comment by thequbit** [comment]
I've got all of the stations pulled in from Wikipedia [here](https://github.com/thequbit/npr_station_scraper/blob/master/stations.json)

I'll pull that into the solution for #91

**Comment by GabeIsman** [comment]
Nice! That's not really test data though, that's just seed data. I don't know if there's a distinction, but either way it's awesome!

**Pull request merged**
