### PR TITLE
Organization Page Roughed In

### PR DESCRIPTION
**Pull request by GabeIsman**
This is infrastructure for the organization page, as well as rough visual components.

I'm using fake data for the collections. But it's also making the real requests (and just dropping the 404's on the floor), so it should be easy to integrate for real.

The visuals will need some iteration, but my hope is that structure is fairly solid.

I spent a bit of time working on a fairly general tile component. Should be reusable across many pages (in whatever form the final visual takes).

Screenshots:
Banner:
screenshot 2015-11-30 16 16 48

Expanded details: 
screenshot 2015-11-30 16 29 42

Mobile widths:
screenshot 2015-11-30 16 17 10

Hover state:
screenshot 2015-11-30 16 18 07

### CODE REVIEW

**Comment by GabeIsman** [comment]
@melodykramer @nkkl wanna take a look at this too?

**Comment by thequbit** [comment]
Oooo! I'll pull down and review this evening.

**Comment by nkkl** [comment]
This is awesome!

Some thoughts about the header:
hero
longtext

And our hover states:
hover

**Comment by GabeIsman** [comment]
@nkkl Fixed it up a bit based on your suggestions, thanks! I did away with the short description/long description distinction; the short description is now just a truncated version of the long one. I think that's better. Updated screenshots below.

screenshot 2015-11-30 17 26 44
screenshot 2015-11-30 17 27 06

**Comment by nkkl** [comment]
Yes this is amazing.

**Comment by thequbit** [comment]
Hmm,have we lost the ability to add a new organization by going to #/organizations/new ?  That doesn't appear to work on this branch ( for me ).

Thoughts @GabeIsman ?

**Comment by thequbit** [comment]
Additionally, I'm getting `TypeError: this.collection is undefined` in the console shortly after the page loads.

**Comment by GabeIsman** [comment]
Communicated over gitter, but just for the record, that issue should be resolved now.

**Comment by thequbit** [comment]
:+1: Looks like there is a bug with the #/organizations/new page with `short_description` not being sent/available.  Going to accept this, and open a ticket.  Looking great @GabeIsman and @nkkl!

**Comment by melodykramer** [comment]
I LOVE THIS.

**Pull request merged**
