### PR TITLE
Mockup of organization home page

### PR DESCRIPTION
**Pull request by nkkl**
- Redesigned the header to take up less real estate
- Mobile and Desktop versions
- Icons need to be cleaned up; will provide assets separately.

### CODE REVIEW

**Comment by nkkl** [comment]
Oh god I'm in the wrong branch.

**Comment by thequbit** [comment]
@nkkl ha!  Close and resubmit to develop, not master.  That ... is one serious PR.

**Comment by nkkl** [comment]
I'M GOING TO COMMIT EVERYTHING

**Comment by thequbit** [comment]
lawl lawl lawl

**Pull request closed without merging**
