### PR TITLE
Ui mockups

### PR DESCRIPTION
**Pull request by nkkl**
- Redesigned the header to take up less real estate
- Mobile and Desktop versions
- Icons need to be cleaned up; will provide assets separately.

### CODE REVIEW

**Comment by nkkl** [comment]
I never thought I'd have a reason to say that rebase saved me.

**Comment by thequbit** [comment]
@nkkl++

Will merge in AM when not on mobile.

**Comment by GabeIsman** [comment]
++ for batman. Looks good!

**Comment by GabeIsman** [comment]
@nkkl I like the smaller header. I'm still wondering about navigation. It seems like there should be a way to jump to a page (like search, or the list of organizations).

**Comment by nkkl** [comment]
Yeah, I agree. Let's take a look at that after churning through the
remaining open design tasks!

Can you do me a favor and file an issue on me for that? 😉

@nkkl
323.205.6533

**Pull request merged**
