### PR TITLE
Client authentication

### LINKED ISSUE #97: Figure out client authentication workflow
There should be a way to log in through the client, and the client should be sending cookies (or Javascript Web Tokens, or something similar) to the server. This is not currently working.

### PR DESCRIPTION
**Pull request by GabeIsman**
Very basic AJAX login/signup/logout functionality. Seems to be working solidly, just missing some UI bells and whistles.

There is currently no login/signup page (which there should be). It all just lives in the header.

Also worth noting that this depends on the fact that the client and server are being served from the same host (different ports are fine). So if you're doing some clever hostfile tricks or something in your local environment, you are likely to run into trouble.

Also included in this PR: a 'flash' component for adding messages to views, a couple of bug fixes for collections on org pages, and a few random cleanup things that I saw here and there.

Fixes #97 and #147.

### CODE REVIEW

**Comment by thequbit** [comment]
@GabeIsman this looks awesome!  So When I'm at the "Thanks for signing up! Please complete your profile." page, when I hit "Save", I get 1 400 error to `/login` to the backend.  I think this should probably be going to `/users`, yes?

I did some digging, but I couldn't find where the route was set :/

**Comment by thequbit** [comment]
Maybe [here](https://github.com/mediapublic/mediapublic/blob/client-authentication/client/app/services/userservice.js#L7) ?  Should be to /users as a different end point?

**Comment by GabeIsman** [comment]
Ah yes. Must be a problem with the signup view pulling in the wrong model.

TD Edit: removed email chain

**Comment by GabeIsman** [comment]
Fixed the issue with the PUT going to '/login' by copying the current user attributes over to a generic person model, but ran into the basic problem that the front-end makes no distinction between a 'person' and a 'user', so the PUT to '/people' with a user's uuid also fails. I think fixing this issue is blocked by #108, which needs fixing anyway. I'd rather just fix the underlying issue than add a hack to deal with it.

In any case let's not let this issue hold up merging this. We can sort this out whenever we get to a more polished sign up flow. I just want to get authentication into the develop so other things can start using it.

**Comment by thequbit** [comment]
Merging, and opening Issue with #108.

**Pull request merged**
