### PR TITLE
Search datasets

### PR DESCRIPTION
**Pull request by GabeIsman**
This adds help requests and removes recordings from the searched over datasets.

Also includes the linter stuff because that touched everything and I didn't want to deal with conflicts.

### CODE REVIEW

**Comment by thequbit** [comment]
On the `/#signup` page, there isn't a save button.  Did that get taken out intentionally?

**Comment by thequbit** [comment]
Also looks like in the search nothing comes up in the little drop down ( suggestions ), but the box does show up.

media-public-drop-down-search

is that correct?

**Comment by GabeIsman** [comment]
Both actually issues introduced in earlier PRs :), oops! When I moved the search view into the banner it inherited some new styles, particularly 'color: #fff', gotta love css. And the signup issue was a race condition causing the view to think that the current user wasn't him or her self and not rendering any buttons.

**Comment by thequbit** [comment]
ha! that css issue is solid.  so dumb.  This looks great!

**Pull request merged**
