### PR TITLE
Contributor code of conduct

### PR DESCRIPTION
**Pull request by ryansb**
This is the CoC from http://contributor-covenant.org/ , please review and let me know if there are changes or additions you'd like.

### CODE REVIEW

**Comment by thequbit** [comment]
@ismcodes @GabeIsman @nkkl @melodykramer  can you comment here saying that you approve the CoC?  Thanks!

**Comment by thequbit** [comment]
I approve!

**Comment by ismcodes** [comment]
Sounds good!

**Comment by GabeIsman** [comment]
I approve!

**Comment by nkkl** [comment]
Looks great! I approve.

**Comment by thequbit** [comment]
@melodykramer - ping on this :).

**Comment by thequbit** [comment]
@melodykramer is this good with yoooooouuuuuuuu!!!!?????? :p

**Pull request merged**
