### PR TITLE
added ability to query via GET params

### PR DESCRIPTION
**Pull request by thequbit**
( also added gabbits for social-meda's that I forgot in last PR - oops! )

### CODE REVIEW

**Comment by thequbit** [comment]
This gives the ability to:

```
/users?org_id=<org_uuid>
/users?q=<search_term>

/organizations?q=<search_term>

/howtos?org_id=<org_uuid>
/howtos?user_id=<user_uuid>
/howtos?q=<search_term>

/help-requests?org_id=<org_uuid>
/help-requests?user_id=<user_uuid>
/help-requestss?q=<search_term>
```

And not used, but implemented:

```
/blogs?org_id=<org_uuid>
/blogs?user_id=<user_uuid>
/blogs?q=<search_term>
```

Note: I added `organization_id` and `author_id` to `HowTos` because they weren't in there already ... not sure how that one slipped by us.  @GabeIsman let me know if you get tripped up!

**Comment by thequbit** [comment]
Ahh, right so searching.

Postgresql is amazing, and has full text search!  yay!  The problem is that sqlite3 does not, boooo!

So I'm just doing super sloppy `SELECT * FROM table_name WHERE column_name LIKE "%<term>%";` effectively.  Not pretty, but functional for the time being.  It works for finding orgs and people fast, and that's what we'll demo.

**Comment by GabeIsman** [comment]
Nice! We also need people by organization_id.

**Comment by thequbit** [comment]
Err, there aren't people any more just users ... right?

**Comment by GabeIsman** [comment]
Oh of course! My bad.

**Comment by GabeIsman** [comment]
So this does not appear to be working for me. When I include the q=<search> I 400's in response. Same with org_id. Although it ALSO seems to be responding with data (just the empty `{data: []}`).

**Comment by thequbit** [comment]
Err, I made it need to have at least 4 chars in length.  What's you're thought on that?   Return with any length for now?

**Comment by GabeIsman** [comment]
Oh yea, definitely. We're using it for autocomplete.

**Comment by thequbit** [comment]
So I think I need to add ?start=<start_index>&count=<return_count> to the query interface then, because if you type in "W" you're going to get back hundreds of stations.

**Comment by GabeIsman** [comment]
That sounds right. We'll need to actually implement pagination on the frontend at some point. For now you could just limit it to ten results and make pagination a separate issue.

**Comment by thequbit** [comment]
Stand by, implementing now.

**Comment by thequbit** [comment]
@GabeIsman give this a shot.

```
http://0.0.0.0:6543/organizations?start=0&count=25
```

If you don't supply a start or a count, defaults of `start=0` and `count=25` are used.

**Comment by GabeIsman** [comment]
Looks great! Thanks Tim.

**Pull request merged**
