### PR TITLE
Fix route syntax.

### PR DESCRIPTION
**Pull request by GabeIsman**
Looks like Pyramid doesn't want those colons.

http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/urldispatch.html

### CODE REVIEW

**Comment by thequbit** [comment]
hmm, so why don't you think we should have the colons?  It allows for the route to tell the difference between say, something like /foo/:{id} and /foo/bar.  Without the colon, the {id} field would be filled with the text 'bar'.

@ryansb am I correct in saying this?  I know you had seen the routes when you did the re-org, so I can only assume this thought went through your mind as well?

**Comment by GabeIsman** [comment]
Hmm. I didn't think it through that far, I was getting a pyramid
default 404 on /organizations/1 with the colons, and it worked great
without them.

**Comment by thequbit** [comment]
So if you did a POST to /organizations and then did a get to /organizations/:1 you got 404?

**Comment by GabeIsman** [comment]
Aha! No. I was doing a GET to `/organizations/1` with no colon, not
`/organizations/:1`. However, I still think we should merge this because:
1. `/models/{id}` is general best practice for REST (from what I've seen).
   E.g. https://github.com/WhiteHouse/api-standards
2. `/models/{id}` is the default route structure for Backbone, and while we
   could certainly work around it, it might cause some pain..
3. I think stacking resource urls like `/models/othermodels/1` is probably
   bad anyway (can't really think of what that would mean), so we don't need
   to enable that.

**Comment by thequbit** [comment]
@ryansb did actually make this change in the develop branch ( the comments are incorrect, but the routes are correct ).

I'll submit a PR against that branch to fix the comments, and then work on auto-generating API docs.

**Pull request closed without merging**
