### PR TITLE
Add missing depencies

### PR DESCRIPTION
**Pull request by GabeIsman**
Update readme and package.json to reflect missing dependencies.

### CODE REVIEW

**Comment by GabeIsman** [comment]
Added some logging to the build step so you know when the js compilation is done.

**Comment by melodykramer** [comment]
can I merge this?

**Comment by thequbit** [comment]
Let me pull it down and rebuild to test it first.   I will do this tomorrow
and merge if it'd all good.

**Comment by thequbit** [comment]
:+1:

**Pull request merged**
