### PR TITLE
Twitter authentication via OAuth2

### PR DESCRIPTION
**Pull request by ryansb**
This is a pretty major change - it adds a sub-application called [Velruse](http://pythonhosted.org/velruse/) that handles authenticating against Twitter and accepting the OAauth2 handshake. It then exposes token data to our application. 

Currently, all it does is call Twitter, authenticate the user, and store their handle and other information in the database. In the future, logging in will lead new users to a prompt to add their email address and tweak their other profile information as they like.

### CODE REVIEW

**Comment by ryansb** [comment]
Ugh...looks like this breaks all the API tests at the moment. I'll fix those tomorrow. 

The code is pretty ready for review, but there's a lot of it. And I need to do developer docs to go along with these changes, since authn/authz is sort of important.

**Comment by thequbit** [comment]
I think Paste is missing from requirements.txt.

**Comment by thequbit** [comment]
When navigating to /login, and clicking the "Login with Twitter" link, I get the below error on the server.  I believe this is because something is a u'' rather than a b''? maybe?

Edit: this happens when I am logged in with twitter already, and when I do it in an incognito window.  I am running Python 3.4.0.

```
Starting server in PID 5763.
serving on 0.0.0.0:6543 view at http://127.0.0.1:6543
NestedMultiDict([])
2015-09-14 12:22:25,612 INFO  [requests.packages.urllib3.connectionpool][worker 4] Starting new HTTPS connection (1): api.twitter.com
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 46521)
Traceback (most recent call last):
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/pyramid/config/views.py", line 503, in _requestonly_view
    response = getattr(view, attr)(request)
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/velruse/providers/twitter.py", line 88, in login
    resp.status_code, resp.content))
velruse.exceptions.ThirdPartyFailure: Status 401: b'{"errors":[{"code":32,"message":"Could not authenticate you."}]}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 665, in __init__
    self.handle()
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/httpserver.py", line 324, in wsgi_execute
    self.wsgi_write_chunk("Internal Server Error\n")
  File "/home/thequbit/Envs/mediapublic3/lib/python3.4/site-packages/Paste-2.0.2-py3.4.egg/paste/httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/usr/lib/python3.4/socket.py", line 391, in write
    return self._sock.send(b)
TypeError: 'str' does not support the buffer interface
----------------------------------------
```

**Comment by ryansb** [comment]
That looks like a velruse problem, or possibly a paste/velruse problem specific to Python 3.

**Comment by thequbit** [comment]
Rough notes for setting up twitter secrets:
1. Make your instance of mediapublic in your development environment public to the world
   - This can be done via a port forward to 6543 on your router.
   - This does not need to persist all of the time.  It only needs to be public if you want to use OAuth
2. Run your server
3. Go to https://apps.twitter.com/app/new
4. Put in `mediapublic as` the application name
5. Put in `Media Public Development Instance` for the description
6. Put in the github repo as the website: `https://github.com/mediapublic/mediapublic`
7. Put in `http://< your_external_ip >:6543/login` for the Callback URL
   - You'll need to know your external IP address.
   - You'll want to check to make sure that the link you put in produces the right page ( should just be a 'Login with twitter' link ).
8. Read the developers agreement, and if you agree, check the "Yes, I agree" check box.
9. Click "Create your Twitter application"
10. Once the Twitter application has been created, click the "Keys and Access Tokens".
    - Find the Consumer Key and Consumer Secret.
    - Set the appropriate keys in the development.ini file for `provider.twitter.consumer_key` and `provider.twitter.consumer_secret`
11. Restart the server with the new development.ini file secret keys loaded in.
12. Navigate to `http://< your_external_ip >:6543/login` and click the "Login with twitter"
    - Authorize mediapublic to access your twitter account
    - View the output on the browser and the terminal to confirm correct operation ( The browser should say "Welcome @< twitter_handle > Please enter an email to complete your profile.", and the terminal should be some twitter JSON output ).

**_DO NOT COMMIT THESE KEYS TO GITHUB**_

That should be it.  If you are not working on Twitter OAuth stuff, it is advised that you do not keep the application open to the world during development, as incremental builds may not be secure.

**Comment by ryansb** [comment]
This PR is now in a state where it can be merged, but it's still lacking proper documentation. 

It uses velruse, as mentioned earlier, to talk to Twitter and once the user has a principal (set as an encrypted cookie) we can use that to allow/deny them certain actions. 

A rule looks like this `(security.Allow, security.Authenticated, "get")` in this example, any user that has a principal will be allowed to read all resources. The only available actions are security.Allow and security.Deny, but the principals (second argument) are very flexible. They can match groups, user IDs, or auth states. During tests, all authorization is bypassed and all users are allowed to do everything.

The groups I had in mind were: 
- Authenticated (a default principal in Pyramid)
- staff (verified station staff)
- admin (service owners & moderators)

Currently, every user is put in the admin group, in the future I'll change this to get the user's permission level from the UserType db model. 

For more on authn/z in Pyramid, check out:
- [Pyramid security narrative docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#security-chapter)
- [Pyramid.security API docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/security.html)
- Example for [URLdispatch ACLs](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/urldispatch.html#example-3)
- We create a context factory for the [cornice API](http://cornice.readthedocs.org/en/latest/api.html#cornice.service.Service) so we can switch in ACLs based on the authenticated UID and other factors.

**Comment by thequbit** [comment]
Nice!  Great work @ryansb!

Will pull down tomorrow and accept once I have it up and running.  Thanks for putting in all this hard work.

**Comment by thequbit** [comment]
:+1: This looks great @ryansb !  I pulled down and all looks to be working on my end ( twitter keys and all that as well ).  Going to accept this.

**Pull request merged**
