### PR TITLE
Basic client setup

### LINKED ISSUE #22: Add build instructions for client app
Make sure build instructions are clear and concise for building the client app.

### PR DESCRIPTION
**Pull request by GabeIsman**
This is a free-hand sketch of one potential setup for the media public client. It includes a lot of awesome things (ES6! Marionette!) and I think it will be fun to work on. Please try and get it up and running (if you can change the 'this is the homepage' to something else and see it in the browser, you're golden) and let me know how the documentation could be improved!

Closes #22 and #21.

### CODE REVIEW

**Comment by thequbit** [comment]
Awesome!  I'll get on this today.

I also owe you my code ( just a PR ).  Getting it running should be super
quick.

**Comment by thequbit** [comment]
Hmm, so I got everything all setup ( needed to install gulp and gulp-plumber, but other than that the README was good! ).  When I change the template.jade file to "this is home page 2", the `gulp watch` command doesn't spit anything out.  If I re-run it, nothing changes either.

Thoughts?

**Comment by thequbit** [comment]
Never mind - was a caching issue.  This looks great to me!  Accepting.

**Comment by GabeIsman** [comment]
Addressed these notes in #29! Thanks for the review.

**Pull request merged**
