### PR TITLE
Explorations of how to handle tiles

### PR DESCRIPTION
**Pull request by nkkl**
Please give feedback on the tile explorations here! This is just a rough pass at it, but I think these are all workable and have the start of some good microinteractions.

### CODE REVIEW

**Comment by thequbit** [comment]
:+1: these are great!

**Comment by GabeIsman** [comment]
Looks good to me! Do we want (optional) images for recordings and/or howtos?

**Comment by nkkl** [comment]
Not in v1, I think - to keep everything lighter weight. We talked about maybe in the future pulling in images for recordings from the source URL.

**Comment by GabeIsman** [comment]
Gotcha.

**Pull request merged**
