### PR TITLE
Basic organization page

### PR DESCRIPTION
**Pull request by GabeIsman**
There is actually a bunch of stuff in this PR. None of it is what you would call 'done', but I think its better to have some client in develop than the barely-anything that is currently there.
- Adds commented out bootstrap overrides for easy customization.
- Adds an application header, with some menu items
- Adds a config, establishes a pattern for client configuration
- Adds backbone-storage as a way to handle client-side caching of api resources
- Adds an organization route, model, storage, and view
- Adds an `aside` component, establishing a pattern for front-end components

The organization page looks like this:
screenshot 2015-09-25 19 04 28

### CODE REVIEW

**Comment by GabeIsman** [comment]
@thequbit or @ryansb wanna take a look at this?

**Comment by thequbit** [comment]
@GabeIsman sorry I took so long to get to this :(.

If I checkout your branch, and run the server using pserve development.ini, and then run the client with http-server, I get CORS errors.   Thoughts?

**Comment by thequbit** [comment]
Also, looks like font-awesome's css file is not being loaded.

**Comment by GabeIsman** [comment]
@thequbit Probably need to merge in develop? I'm not sure. I'll take a look in the morning.

**Comment by GabeIsman** [comment]
@thequbit Sorry for dropping the ball on this! Just as I suspected, it just needed the latest from develop.

**Comment by thequbit** [comment]
No worries!  I'll pull down the latest this evening and get back to you with feedback.  Thanks for doing the merge @GabeIsman!

**Comment by thequbit** [comment]
@GabeIsman so I've pulled down the branch, and added an organization to the sqlite database, and got your code up and running using http-server.  How do I navigate to a organization?  Also, when I click on Organizations I don't get a list as I would expect.

**Comment by thequbit** [comment]
Note: I did do `gulp watch` first before running http-server.

**Comment by GabeIsman** [comment]
Yea, I haven't built an organizations list page yet. You have to navigate directly to #/organizations/uuid.

**Comment by thequbit** [comment]
Okay, got it all up and running.  Looks good to me!  Sorry for the unreasonable relay on this, ha.

:+1:

**Pull request merged**
